<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline-17-4360-2001/blob/main/notebooks/F_clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline-17-4360-2001/refs/heads/main/data/raw/F_clientes.csv

**BLOQUE 1:Cargando Archivo e importando Libreria**

In [3]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline-17-4360-2001/refs/heads/main/data/raw/F_clientes.csv"

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [24]:
display(df.head(2))

  id_cliente          cliente                  correo  telefono
0     CL1000  Paola Mendoza 0  cliente061@empresa.com  73372703
1     CL1001  Elena Ramírez 1  cliente186@outlook.com  75447071

**BLOQUE 2: Exploracion del DATASET (Calidad del dato)**

In [17]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

  id_cliente             cliente                  correo  telefono
0     CL1000     Paola Mendoza 0  cliente061@empresa.com  73372703
1     CL1001     Elena Ramírez 1  cliente186@outlook.com  75447071
2     CL1002  Valeria Martínez 2   cliente25@outlook.com  76605966
3     CL1003    Daniela Rivera 3    cliente317@correo.sv  73134898
4     CL1004     Elena Morales 4    cliente426@correo.sv  78399637

In [8]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(145, 4)

In [9]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'cliente', 'correo', 'telefono'], dtype='object')

In [10]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente    object
cliente       object
correo        object
telefono      object
dtype: object

In [11]:
print("Valores nulos")
print(df.isnull().sum())

Valores nulos
id_cliente    0
cliente       0
correo        7
telefono      4
dtype: int64

In [12]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
5

**BLOQUE 3: Limpieza de datos**

In [28]:
clientes = df.copy()

In [13]:
#Elimina espacios al inicio y al final en columnas de texto
for col in clientes.select_dtypes(include="object").columns:clientes[col]=clientes[col].str.strip()

In [15]:
#Normalizar el nombre
clientes["cliente"]=clientes["cliente"].str.title()

In [16]:
#Normalizar el email
clientes['correo']=clientes['correo'].str.lower()

In [22]:
#Normalizar el teléfono para limpiar espacios y estandarizar formato
clientes['telefono']=clientes['telefono'].str.upper().str.replace(' ', '').str.replace('+503', '', 1)

In [29]:
for col in clientes.columns: print(col)

id_cliente
cliente
correo
telefono
motivo_rechazo

In [32]:
display(clientes.head())

  id_cliente             cliente                  correo  telefono
0     CL1000     Paola Mendoza 0  cliente061@empresa.com  73372703
1     CL1001     Elena Ramírez 1  cliente186@outlook.com  75447071
2     CL1002  Valeria Martínez 2   cliente25@outlook.com  76605966
3     CL1003    Daniela Rivera 3    cliente317@correo.sv  73134898
4     CL1004     Elena Morales 4    cliente426@correo.sv  78399637

In [33]:
clientes = clientes.drop_duplicates()

In [34]:
print("Dimensiones del dataset (filas, columnas)")
print(clientes.shape)

Dimensiones del dataset (filas, columnas)
(140, 4)

**SEPARAR DATOS VALIDOS Y RECHAZADOS**

In [37]:
validos = clientes[
    clientes['cliente'].notna() &
    clientes['correo'].notna()
].copy()

In [38]:
rechazados = clientes[
    clientes['cliente'].isna() |
    clientes['correo'].isna()
].copy()

**MOTIVO DEL RECHAZO**

In [39]:
def motivo(row):

    motivos = []

    if pd.isna(row['cliente']):
        motivos.append("nombre_vacio")

    if pd.isna(row['correo']):
        motivos.append("correo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**EXPORTAR ARCHIVOS**

In [40]:
validos.to_csv("clientes_curated.csv", index=False)

In [41]:
rechazados.to_csv("clientes_rejects.csv", index=False)

In [42]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [51]:
# Código para eliminar la tabla 'clientes_curated' y 'clientes_rejects'
from sqlalchemy.sql import text
with engine.connect() as connection:
    connection.execute(text("DROP TABLE IF EXISTS clientes_curated"))
    connection.execute(text("DROP TABLE IF EXISTS clientes_rejects"))
    connection.commit()
print("Tablas 'clientes_curated' y 'clientes_rejects' eliminadas exitosamente (si existían).")

Tablas 'clientes_curated' y 'clientes_rejects' eliminadas exitosamente (si existían).

In [52]:
validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

7

In [53]:
pd.read_sql(
"SELECT * FROM clientes_curated LIMIT 10",
engine
)

  id_cliente             cliente                  correo  telefono
0     CL1000     Paola Mendoza 0  cliente061@empresa.com  73372703
1     CL1001     Elena Ramírez 1  cliente186@outlook.com  75447071
2     CL1002  Valeria Martínez 2   cliente25@outlook.com  76605966
3     CL1003    Daniela Rivera 3    cliente317@correo.sv  73134898
4     CL1004     Elena Morales 4    cliente426@correo.sv  78399637
5     CL1005       Ana Mendoza 5     cliente555gmail.com  78847864
6     CL1006      Andrés López 6  cliente645@outlook.com      None
7     CL1007   Marta Hernández 7  cliente735@empresa.com  72952127
8     CL1008      Diego Torres 8  cliente870@empresa.com  79305719
9     CL1009   Daniela Morales 9    cliente987@gmail.com  79050212