<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline-17-4360-2001/blob/main/notebooks/F_envios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline-17-4360-2001/refs/heads/main/data/raw/F_envios.csv

**BLOQUE 1:Cargando Archivo e importando Libreria**

In [1]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline-17-4360-2001/refs/heads/main/data/raw/F_envios.csv"

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [7]:
display(df.head(2))

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,entregado

**BLOQUE 2: Exploracion del DATASET (Calidad del dato)**

In [5]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,entregado
2,ENV8002,PED7191,"Calle El Mirador, Sonsonate",2024-05-30,devuelto
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-07-03,en ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-01-09,preparando

In [8]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(216, 5)

In [9]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_envio', 'id_pedido', 'direccion', 'fecha_envio', 'estado_envio'], dtype='object')

In [10]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_envio        object
id_pedido       object
direccion       object
fecha_envio     object
estado_envio    object
dtype: object

In [11]:
print("Valores nulos")
print(df.isnull().sum())

Valores nulos
id_envio         0
id_pedido        9
direccion        0
fecha_envio     10
estado_envio     0
dtype: int64

In [12]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
6

**BLOQUE 3: Limpieza de datos**

In [13]:
envios = df.copy()

In [14]:
#Elimina espacios al inicio y al final en columnas de texto
for col in envios.select_dtypes(include="object").columns:envios[col]=envios[col].str.strip()

In [15]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
envios = envios.replace(r'^\s*$', pd.NA, regex=True)

In [17]:
for col in envios.columns: print(col)

id_envio
id_pedido
direccion
fecha_envio
estado_envio

In [18]:
display(envios.head())

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,entregado
2,ENV8002,PED7191,"Calle El Mirador, Sonsonate",2024-05-30,devuelto
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-07-03,en ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-01-09,preparando

In [19]:
envios = envios.drop_duplicates()

In [20]:
print("Dimensiones del dataset (filas, columnas)")
print(envios.shape)

Dimensiones del dataset (filas, columnas)
(210, 5)

**SEPARAR DATOS VALIDOS Y RECHAZADOS**

In [21]:
validos = envios[
    envios['id_envio'].notna() &
    envios['id_pedido'].notna()
].copy()

In [22]:
rechazados = envios[
    envios['id_envio'].isna() |
    envios['id_pedido'].isna()
].copy()

**MOTIVO DEL RECHAZO**

In [23]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_envio']):
        motivos.append("IDenvio_vacio")

    if pd.isna(row['id_pedido']):
        motivos.append("IDpedido_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**EXPORTAR ARCHIVOS**

In [24]:
validos.to_csv("envios_curated.csv", index=False)

In [25]:
rechazados.to_csv("envios_rejects.csv", index=False)

In [26]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 59.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [27]:
validos.to_sql(
    'envios_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'envios_rejects',
    engine,
    if_exists='append',
    index=False
)

8

In [28]:
pd.read_sql(
"SELECT * FROM envios_curated LIMIT 10",
engine
)

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-06-02,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-05-07,entregado
2,ENV8002,PED7191,"Calle El Mirador, Sonsonate",2024-05-30,devuelto
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-07-03,en ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-01-09,preparando
5,ENV8005,PED7008,"Pje. Las Flores, Sonsonate",2024-03-03,devuelto
6,ENV8006,PED7169,"Av. Roosevelt, San Salvador",2024-04-04,devuelto
7,ENV8007,PED7153,"Calle Principal, Usulután",2024-09-07,devuelto
8,ENV8008,PED7207,"Calle Principal, San Salvador",2025-04-23,en ruta
9,ENV8009,PED7103,"Boulevard Constitución, Santa Ana",2025-05-07,entregado