https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline-17-4360-2001/refs/heads/main/data/raw/F_pedidos.csv

**BLOQUE 1:Cargando Archivo e importando Libreria**

In [1]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline-17-4360-2001/refs/heads/main/data/raw/F_pedidos.csv"

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [6]:
display(df.head(2))

  id_pedido id_cliente fecha_pedido    monto     estado
0   PED7000     CL1138   2024-11-28  1984.03   enviado
1   PED7001        NaN   2025-01-31  2395.24  cancelado

**BLOQUE 2: Exploracion del DATASET (Calidad del dato)**

In [7]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

  id_pedido id_cliente fecha_pedido    monto     estado
0   PED7000     CL1138   2024-11-28  1984.03   enviado
1   PED7001        NaN   2025-01-31  2395.24  cancelado
2   PED7002     CL1067   2024-07-13   433.46  cancelado
3   PED7003     CL1097   2025-05-02   352.01  cancelado
4   PED7004     CL1068   2024-12-20  1182.84    enviado

In [8]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(236, 5)

In [9]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_pedido', 'id_cliente', 'fecha_pedido', 'monto', 'estado'], dtype='object')

In [10]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_pedido       object
id_cliente      object
fecha_pedido    object
monto           object
estado          object
dtype: object

In [11]:
print("Valores nulos")
print(df.isnull().sum())

Valores nulos
id_pedido       0
id_cliente      6
fecha_pedido    5
monto           6
estado          0
dtype: int64

In [12]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
6

**BLOQUE 3: Limpieza de datos**

In [13]:
pedidos = df.copy()

In [14]:
#Elimina espacios al inicio y al final en columnas de texto
for col in pedidos.select_dtypes(include="object").columns:pedidos[col]=pedidos[col].str.strip()

In [15]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
pedidos = pedidos.replace(r'^\s*$', pd.NA, regex=True)

In [16]:
for col in pedidos.columns: print(col)

id_pedido
id_cliente
fecha_pedido
monto
estado

In [17]:
display(pedidos.head())

  id_pedido id_cliente fecha_pedido    monto     estado
0   PED7000     CL1138   2024-11-28  1984.03    enviado
1   PED7001        NaN   2025-01-31  2395.24  cancelado
2   PED7002     CL1067   2024-07-13   433.46  cancelado
3   PED7003     CL1097   2025-05-02   352.01  cancelado
4   PED7004     CL1068   2024-12-20  1182.84    enviado

In [18]:
pedidos = pedidos.drop_duplicates()

In [19]:
print("Dimensiones del dataset (filas, columnas)")
print(pedidos.shape)

Dimensiones del dataset (filas, columnas)
(230, 5)

**SEPARAR DATOS VALIDOS Y RECHAZADOS**

In [20]:
validos = pedidos[
    pedidos['id_pedido'].notna() &
    pedidos['id_cliente'].notna()
].copy()

In [21]:
rechazados = pedidos[
    pedidos['id_pedido'].isna() |
    pedidos['id_cliente'].isna()
].copy()

**MOTIVO DEL RECHAZO**

In [22]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_pedido']):
        motivos.append("IDpedido_vacio")

    if pd.isna(row['id_cliente']):
        motivos.append("IDcliente_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**EXPORTAR ARCHIVOS**

In [23]:
validos.to_csv("pedidos_curated.csv", index=False)

In [24]:
rechazados.to_csv("pedidos_rejects.csv", index=False)

In [25]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 51.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [26]:
validos.to_sql(
    'pedidos_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'pedidos_rejects',
    engine,
    if_exists='append',
    index=False
)

6

In [27]:
pd.read_sql(
"SELECT * FROM pedidos_curated LIMIT 10",
engine
)

  id_pedido id_cliente fecha_pedido    monto       estado
0   PED7000     CL1138   2024-11-28  1984.03      enviado
1   PED7002     CL1067   2024-07-13   433.46    cancelado
2   PED7003     CL1097   2025-05-02   352.01    cancelado
3   PED7004     CL1068   2024-12-20  1182.84      enviado
4   PED7005     CL1030   2024-04-02   2154.6  preparacion
5   PED7006     CL1091   2025-03-05  1921.17      enviado
6   PED7007     CL1086   2024-10-21  1402.07  preparacion
7   PED7008     CL1002   2024-08-04   404.61  preparacion
8   PED7009     CL1084   2024-03-30   987.29    pendiente
9   PED7010     CL1059   2024-06-16  1802.57    cancelado